name: test-library
on:
  push

jobs:
  build:
    env:
      BUILD_PYTHON_VERSION: '3.8'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.BUILD_PYTHON_VERSION }}
          cache: poetry
      - name: Install dependencies
        run: | 
          poetry install
        
      - name: Run linting
        run: |
          poetry run python -m pylint ./test_dependabot
